### ISSUE TITLE
Owl -> Borgor

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/Owl#5]
# Rewrite/refactor
I am going to rewrite this project in Python (prototype) then switch the language over to Go/C++/C.

## Todo
- [ ] Remove current codebase
- [ ] Rewrite README.md
- [ ] Remove stale branches
- [ ] Design prototype architecture 
- [ ] Plan commands, functions, classes, etc
- [ ] Write API wrapper for RPS API -> rpsapi.py (library)
- [ ] Write package manager 😎 
- [ ] List flaws in design
- [ ] New rewrite in Go/C++
